services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: nn_user
      POSTGRES_PASSWORD: nn_pass
      POSTGRES_DB: nn_chat
    ports:
      - "5432:5432"
    volumes:
      - ../nn-chat-db:/var/lib/postgresql/data
      
volumes:
 node_modules: